import PDFDocument from "pdfkit";
import { prisma } from "../config/prisma";
import { AnalyticsService } from "./analyticsService";

export class PDFService {
  static async generateMonthlyReport(userId: string): Promise<Buffer> {
    const user = await prisma.user.findUnique({ where: { id: userId } });
    const summary = await AnalyticsService.getSummary(userId);
    const categoryBreakdown = await AnalyticsService.getCategoryBreakdown(userId);
    const expenses = await prisma.expense.findMany({
      where: { userId },
      include: { category: true },
      orderBy: { date: "desc" },
      take: 15,
    });

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Brand Header
      doc.fillColor("#1E293B").fontSize(24).text("Financial Statement & Expense Summary", { align: "left" });
      doc.fontSize(10).fillColor("#64748B").text(`Generated for: ${user?.name || "Valued User"} (${user?.email})`);
      doc.text(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
      doc.moveDown();

      // Divider Line
      doc.strokeColor("#E2E8F0").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // Summary Cards
      doc.fillColor("#0F172A").fontSize(14).text("Monthly Performance Summary", { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(11).fillColor("#334155");
      doc.text(`Total Monthly Income: $${summary.currentMonth.income.toFixed(2)}`);
      doc.text(`Total Monthly Expenses: $${summary.currentMonth.expenses.toFixed(2)}`);
      doc.text(`Net Monthly Savings: $${summary.currentMonth.netSavings.toFixed(2)}`);
      doc.text(`Savings Rate: ${summary.currentMonth.savingsRate}%`);
      doc.text(`Overall Account Balance: $${summary.allTime.totalBalance.toFixed(2)}`);
      doc.moveDown();

      // Category Breakdown Table
      doc.fillColor("#0F172A").fontSize(14).text("Top Expense Categories", { underline: true });
      doc.moveDown(0.5);

      categoryBreakdown.slice(0, 5).forEach((cat) => {
        doc.fontSize(10).fillColor("#475569").text(`• ${cat.name}: $${cat.amount.toFixed(2)}`);
      });
      doc.moveDown();

      // Recent Transactions Table Header
      doc.fillColor("#0F172A").fontSize(14).text("Recent Expense Activity", { underline: true });
      doc.moveDown(0.5);

      const tableTop = doc.y;
      doc.fontSize(10).fillColor("#1E293B").text("Date", 50, tableTop, { bold: true } as any);
      doc.text("Description", 150, tableTop);
      doc.text("Category", 350, tableTop);
      doc.text("Amount", 480, tableTop, { align: "right" });

      doc.strokeColor("#CBD5E1").lineWidth(0.5).moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();

      let y = tableTop + 25;
      expenses.forEach((exp) => {
        if (y > 700) {
          doc.addPage();
          y = 50;
        }
        doc.fontSize(9).fillColor("#334155");
        doc.text(new Date(exp.date).toLocaleDateString(), 50, y);
        doc.text(exp.description.length > 25 ? exp.description.substring(0, 22) + "..." : exp.description, 150, y);
        doc.text(exp.category.name, 350, y);
        doc.text(`$${exp.amount.toFixed(2)}`, 480, y, { align: "right" });
        y += 18;
      });

      // Footer
      doc.fontSize(8).fillColor("#94A3B8").text("Generated by Expense Tracker with Analytics - Computer Science Portfolio Project", 50, 740, { align: "center" });

      doc.end();
    });
  }
}
